project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "The_Impact_of_COVID_On_Education"
  author:
    - Riya Mhatre (rnm2134)
    - Aarya Dharm (add2180)
  repo-url: https://github.com/riyamhatre/The_Impact_of_COVID_On_Education
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


